.TH "CHO2TXT 1" "July 2023" "User Commands"
.SH NAME
cho2txt - Extract lyrics from chordpro files
.SH SYNOPSIS
.B cho2txt
[-t]
[-d]
[-h]
[-v]
[FILE]...
.SH DESCRIPTION
.PP
Provide one or more chordpro files as arguments
or pipe the content of one or more chordpro files via stdin.
The lyrics will be extracted and '\\n', '\\t', '\\r' and ' '
will be trimmed at the beginning and the end.
Also lines containing no lyrics and only chordpro directives will be removed.
The resulting text will be printed to stdout.
.TP
\fB\,-t\/\fR, \fB\,--title\/\fR
Print the title of the song, e.g. 'Love Me Tender'.
.TP
\fB\,-d\/\fR, \fB\,--directive\/\fR
Print the title of the song as chordpro directive, e.g. '{title: Love Me Tender}'
.TP
\fB\,-h\/\fR, \fB\,--help\/\fR
Print help information.
.TP
\fB\,-v\/\fR, \fB\,--version\/\fR
Print program version to stdout.
.SH EXAMPLES
.sp
.RS 4
cat Love_Me_Tender.cho "You_ll_Never_Walk_Alone.cho" | cho2txt

cho2txt -t Love_Me_Tender.cho
