.TH "CHO2TXT 1" "June 2023" "User Commands"
.SH NAME
cho2txt - Extract lyrics from chordpro files
.SH SYNOPSIS
.B cho2txt
[ filepath ]
.SH DESCRIPTION
.PP
Provide a chordpro file via the first argument or pipe the contents of the chordpro file via stdin.
The lyrics will be extracted and '\\n', '\\t', '\\r' and ' ' will be trimmed at the beginning and the end.
